### ISSUE TITLE
Downloading Gcode

### ISSUE THREAD

**Issue by sankafola** [Sindarius/DuetWebControl#1]
i tried Imac and Window 10 , chrome new ver and firefox and safari , SBC update give the same 

i get Downloading GCODE and then if i press on reload scene i get " processing Gcode " 

i tried both Cura and ideamaker

**Comment by Sindarius** [comment]
The issue is do to a url difference between the SBC and SD versions of the DWC that I missed. I am working on a fix that should address the issue.

**Comment by danym21** [comment]
@Sindarius many thanks that you work on it.
looks like the Fix is not working :-(
as example when I try to open a File like "CFFFP_top_V4.gcode"
this link is creates:
X.X.X.X = my printer IP
http://X.X.X.X/viewer.html?filepath=0:/gcodes/CFFFP_top_V4.gcode&printerip=X.X.X.X&sbc=true
the viewer will be opened, with the following error message:
Failed to download gcode http://X.X.X.X/rr_download?name=0:/gcodes/CFFFP_top_V4.gcode

when you need aditional Information I´m glad to help.

**Comment by Sindarius** [comment]
I appreciate it. I was hoping a little fix I tried was going to do it. I am going to take a slightly different approach to resolve the problem.  My hope was to have the DWC tell the viewer if it was running SD or SBC which has different end points. That didn't work out the way I hoped so I am going to test both end points in the viewer and see if that works.

**Comment by Sindarius** [comment]
I have taken a different approach that should hopefully resolve the problem. Please give this a shot and let me know

https://github.com/Sindarius/DuetWebControl/releases/tag/3.1.1-SBCFixV2

**Comment by danym21** [comment]
@Sindarius 
Many thx this time it worked :-)

**Comment by Sindarius** [comment]
Awesome thanks for the feedback

**Comment by sankafola** [comment]
works now thanks a lot
